packages:
  - 'core-api'
  - 'console'

onlyBuiltDependencies:
  - '@scarf/scarf'
  - '@swc/core'
  - 'esbuild'
  - 'grpc-tools'
  - 'msgpackr-extract'
  - 'msw'
  - 'protobufjs'
allowBuilds:
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  grpc-tools: true
  msgpackr-extract: true
  msw: true
  protobufjs: true
