version: "3"
dotenv: ["core-api/.env"]
includes:
  api:
    taskfile: ./core-api/taskfile.yml
    dir: ./core-api
  console:
    taskfile: ./console/taskfile.yml
    dir: ./console

  worker:
    taskfile: ./worker/taskfile.yml
    dir: ./worker

tasks:
  dev:
    cmds:
      - task api:dev &
      - task console:dev &
      - |
        echo "Waiting for API to be ready..."
        until curl -s http://localhost:$PORT > /dev/null; do
          sleep 1
        done
        echo "API is up! Starting worker..."
      - task worker:dev

  build:
    deps:
      - api:build
      - console:build
  prod:
    deps:
      - api:prod
  install:
    deps:
      - api:install
      - console:instal
  gen-api:
    cmd: npx swagger-typescript-api generate -n api.ts -p ./open-api/open-api.json -o ./worker/services/core-api --route-types --axios --extract-enums --unwrap-response-data --default-response any --module-name-index 1000
