version: '3'
dotenv: ['core-api/.env', 'worker/.env', 'console/.env']
includes:
  api:
    taskfile: ./core-api/taskfile.yml
    dir: ./core-api
  console:
    taskfile: ./console/taskfile.yml
    dir: ./console
  worker:
    taskfile: ./worker/taskfile.yml
    dir: ./worker

tasks:
  # Development environment setup and start
  # Starts both API and console development servers with hot-reload enabled
  # Environment: development mode
  dev:
    deps:
      - api:dev
      - console:dev

  # Production build
  # Creates optimized production builds for both API and console applications
  # Includes minification and bundling for both services
  build:
    deps:
      - api:build
      - console:build
      - worker:build
  # Production deployment
  # Starts the production server for the API service
  # Environment: production mode
  prod:
    deps:
      - api:prod

  # Run tests
  # Executes unit and integration tests for both API and console applications
  # Runs tests in parallel for both services
  test:
    deps:
      - api:test
      # - console:test

  # Install dependencies
  # Installs all project dependencies from package.json files
  # Sets up husky for git hooks and installs dependencies for all services
  install:
    cmds:
      - npm install -D husky
      - task: api:install
      - task: console:install
      - task: worker:install

  # API documentation generation
  # Generates API documentation after ensuring API server is ready
  # Waits for API server health check before generating docs
  gen-api:
    cmds:
      - npx swagger-typescript-api generate -n api.ts -p ./.open-api/open-api.json -o ./worker/services/core-api --route-types --axios --extract-enums --unwrap-response-data --default-response any --module-name-index 1000
      - cd console && task gen-api

  # Docker Compose orchestration
  # Starts all services using docker compose with environment variables
  # Builds and recreates containers with 3 worker instances
  docker-compose:
    cmds:
      - |
        docker compose --env-file ./core-api/.env up -d --build --force-recreate --scale worker=3

  # Project initialization
  # Sets up environment files and initializes the development environment
  # Copies example env files and starts required infrastructure services
  init:
    cmds:
      - node -e "require('fs').copyFileSync('core-api/example.env', 'core-api/.env')"
      - node -e "require('fs').copyFileSync('worker/example.env', 'worker/.env')"
      - node -e "require('fs').copyFileSync('console/example.env', 'console/.env')"
      - docker compose up -d postgres redis --force-recreate
    deps:
      - install
      - worker:tools

  # Protocol buffer generation
  # Generates TypeScript code from protocol buffer definitions
  # Updates API client和服务 definitions based on proto files
  proto:
    cmds:
      - task: api:proto

  # Clean build artifacts
  # Removes all node_modules and build artifacts from all services
  # Cleans up generated files and temporary build outputs
  clean:
    cmds:
      - rm -rf ./node_modules
      - task: api:clean
      - task: console:clean
      - task: worker:clean
