version: "3"

includes:
  api:
    taskfile: ./core-api/taskfile.yml
    dir: ./core-api
  console:
    taskfile: ./console/taskfile.yml
    dir: ./console

tasks:
  dev:
    deps:
      - api:dev
      - console:dev
  build:
    deps:
      - api:build
      - console:build
  prod:
    deps:
      - api:prod
  install:
    deps:
      - api:install
      - console:instal
  gen-api:
    cmd: npx swagger-typescript-api generate -n index.ts -p ./open-api/open-api.json -o ./worker/services/core-api --route-types --axios --extract-enums --unwrap-response-data --default-response any --module-name-index 1000
