// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: jobs_registry.proto

package jobs_registry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobsRegistryService_Next_FullMethodName                  = "/jobs_registry.JobsRegistryService/Next"
	JobsRegistryService_Result_FullMethodName                = "/jobs_registry.JobsRegistryService/Result"
	JobsRegistryService_ResultSubdomains_FullMethodName      = "/jobs_registry.JobsRegistryService/ResultSubdomains"
	JobsRegistryService_ResultHttpProbe_FullMethodName       = "/jobs_registry.JobsRegistryService/ResultHttpProbe"
	JobsRegistryService_ResultPorts_FullMethodName           = "/jobs_registry.JobsRegistryService/ResultPorts"
	JobsRegistryService_ResultVulnerabilities_FullMethodName = "/jobs_registry.JobsRegistryService/ResultVulnerabilities"
	JobsRegistryService_ResultScreenshot_FullMethodName      = "/jobs_registry.JobsRegistryService/ResultScreenshot"
	JobsRegistryService_ResultClassifier_FullMethodName      = "/jobs_registry.JobsRegistryService/ResultClassifier"
	JobsRegistryService_ResultAssistant_FullMethodName       = "/jobs_registry.JobsRegistryService/ResultAssistant"
)

// JobsRegistryServiceClient is the client API for JobsRegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service Definition
type JobsRegistryServiceClient interface {
	Next(ctx context.Context, in *Worker, opts ...grpc.CallOption) (*Job, error)
	// DEPRECATED: Use category-specific RPCs
	Result(ctx context.Context, in *JobResultRequest, opts ...grpc.CallOption) (*JobResponse, error)
	// Category-specific result RPCs
	ResultSubdomains(ctx context.Context, in *SubdomainResultRequest, opts ...grpc.CallOption) (*JobResponse, error)
	ResultHttpProbe(ctx context.Context, in *HttpProbeResultRequest, opts ...grpc.CallOption) (*JobResponse, error)
	ResultPorts(ctx context.Context, in *PortsResultRequest, opts ...grpc.CallOption) (*JobResponse, error)
	ResultVulnerabilities(ctx context.Context, in *VulnerabilitiesResultRequest, opts ...grpc.CallOption) (*JobResponse, error)
	ResultScreenshot(ctx context.Context, in *ScreenshotResultRequest, opts ...grpc.CallOption) (*JobResponse, error)
	ResultClassifier(ctx context.Context, in *ClassifierResultRequest, opts ...grpc.CallOption) (*JobResponse, error)
	ResultAssistant(ctx context.Context, in *AssistantResultRequest, opts ...grpc.CallOption) (*JobResponse, error)
}

type jobsRegistryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobsRegistryServiceClient(cc grpc.ClientConnInterface) JobsRegistryServiceClient {
	return &jobsRegistryServiceClient{cc}
}

func (c *jobsRegistryServiceClient) Next(ctx context.Context, in *Worker, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, JobsRegistryService_Next_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsRegistryServiceClient) Result(ctx context.Context, in *JobResultRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, JobsRegistryService_Result_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsRegistryServiceClient) ResultSubdomains(ctx context.Context, in *SubdomainResultRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, JobsRegistryService_ResultSubdomains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsRegistryServiceClient) ResultHttpProbe(ctx context.Context, in *HttpProbeResultRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, JobsRegistryService_ResultHttpProbe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsRegistryServiceClient) ResultPorts(ctx context.Context, in *PortsResultRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, JobsRegistryService_ResultPorts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsRegistryServiceClient) ResultVulnerabilities(ctx context.Context, in *VulnerabilitiesResultRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, JobsRegistryService_ResultVulnerabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsRegistryServiceClient) ResultScreenshot(ctx context.Context, in *ScreenshotResultRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, JobsRegistryService_ResultScreenshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsRegistryServiceClient) ResultClassifier(ctx context.Context, in *ClassifierResultRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, JobsRegistryService_ResultClassifier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsRegistryServiceClient) ResultAssistant(ctx context.Context, in *AssistantResultRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, JobsRegistryService_ResultAssistant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobsRegistryServiceServer is the server API for JobsRegistryService service.
// All implementations must embed UnimplementedJobsRegistryServiceServer
// for forward compatibility.
//
// Service Definition
type JobsRegistryServiceServer interface {
	Next(context.Context, *Worker) (*Job, error)
	// DEPRECATED: Use category-specific RPCs
	Result(context.Context, *JobResultRequest) (*JobResponse, error)
	// Category-specific result RPCs
	ResultSubdomains(context.Context, *SubdomainResultRequest) (*JobResponse, error)
	ResultHttpProbe(context.Context, *HttpProbeResultRequest) (*JobResponse, error)
	ResultPorts(context.Context, *PortsResultRequest) (*JobResponse, error)
	ResultVulnerabilities(context.Context, *VulnerabilitiesResultRequest) (*JobResponse, error)
	ResultScreenshot(context.Context, *ScreenshotResultRequest) (*JobResponse, error)
	ResultClassifier(context.Context, *ClassifierResultRequest) (*JobResponse, error)
	ResultAssistant(context.Context, *AssistantResultRequest) (*JobResponse, error)
	mustEmbedUnimplementedJobsRegistryServiceServer()
}

// UnimplementedJobsRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobsRegistryServiceServer struct{}

func (UnimplementedJobsRegistryServiceServer) Next(context.Context, *Worker) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method Next not implemented")
}
func (UnimplementedJobsRegistryServiceServer) Result(context.Context, *JobResultRequest) (*JobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Result not implemented")
}
func (UnimplementedJobsRegistryServiceServer) ResultSubdomains(context.Context, *SubdomainResultRequest) (*JobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResultSubdomains not implemented")
}
func (UnimplementedJobsRegistryServiceServer) ResultHttpProbe(context.Context, *HttpProbeResultRequest) (*JobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResultHttpProbe not implemented")
}
func (UnimplementedJobsRegistryServiceServer) ResultPorts(context.Context, *PortsResultRequest) (*JobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResultPorts not implemented")
}
func (UnimplementedJobsRegistryServiceServer) ResultVulnerabilities(context.Context, *VulnerabilitiesResultRequest) (*JobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResultVulnerabilities not implemented")
}
func (UnimplementedJobsRegistryServiceServer) ResultScreenshot(context.Context, *ScreenshotResultRequest) (*JobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResultScreenshot not implemented")
}
func (UnimplementedJobsRegistryServiceServer) ResultClassifier(context.Context, *ClassifierResultRequest) (*JobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResultClassifier not implemented")
}
func (UnimplementedJobsRegistryServiceServer) ResultAssistant(context.Context, *AssistantResultRequest) (*JobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResultAssistant not implemented")
}
func (UnimplementedJobsRegistryServiceServer) mustEmbedUnimplementedJobsRegistryServiceServer() {}
func (UnimplementedJobsRegistryServiceServer) testEmbeddedByValue()                             {}

// UnsafeJobsRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobsRegistryServiceServer will
// result in compilation errors.
type UnsafeJobsRegistryServiceServer interface {
	mustEmbedUnimplementedJobsRegistryServiceServer()
}

func RegisterJobsRegistryServiceServer(s grpc.ServiceRegistrar, srv JobsRegistryServiceServer) {
	// If the following call panics, it indicates UnimplementedJobsRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobsRegistryService_ServiceDesc, srv)
}

func _JobsRegistryService_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Worker)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsRegistryServiceServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsRegistryService_Next_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsRegistryServiceServer).Next(ctx, req.(*Worker))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsRegistryService_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsRegistryServiceServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsRegistryService_Result_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsRegistryServiceServer).Result(ctx, req.(*JobResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsRegistryService_ResultSubdomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubdomainResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsRegistryServiceServer).ResultSubdomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsRegistryService_ResultSubdomains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsRegistryServiceServer).ResultSubdomains(ctx, req.(*SubdomainResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsRegistryService_ResultHttpProbe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpProbeResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsRegistryServiceServer).ResultHttpProbe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsRegistryService_ResultHttpProbe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsRegistryServiceServer).ResultHttpProbe(ctx, req.(*HttpProbeResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsRegistryService_ResultPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortsResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsRegistryServiceServer).ResultPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsRegistryService_ResultPorts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsRegistryServiceServer).ResultPorts(ctx, req.(*PortsResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsRegistryService_ResultVulnerabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VulnerabilitiesResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsRegistryServiceServer).ResultVulnerabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsRegistryService_ResultVulnerabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsRegistryServiceServer).ResultVulnerabilities(ctx, req.(*VulnerabilitiesResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsRegistryService_ResultScreenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenshotResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsRegistryServiceServer).ResultScreenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsRegistryService_ResultScreenshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsRegistryServiceServer).ResultScreenshot(ctx, req.(*ScreenshotResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsRegistryService_ResultClassifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifierResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsRegistryServiceServer).ResultClassifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsRegistryService_ResultClassifier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsRegistryServiceServer).ResultClassifier(ctx, req.(*ClassifierResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsRegistryService_ResultAssistant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssistantResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsRegistryServiceServer).ResultAssistant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsRegistryService_ResultAssistant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsRegistryServiceServer).ResultAssistant(ctx, req.(*AssistantResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobsRegistryService_ServiceDesc is the grpc.ServiceDesc for JobsRegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobsRegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jobs_registry.JobsRegistryService",
	HandlerType: (*JobsRegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Next",
			Handler:    _JobsRegistryService_Next_Handler,
		},
		{
			MethodName: "Result",
			Handler:    _JobsRegistryService_Result_Handler,
		},
		{
			MethodName: "ResultSubdomains",
			Handler:    _JobsRegistryService_ResultSubdomains_Handler,
		},
		{
			MethodName: "ResultHttpProbe",
			Handler:    _JobsRegistryService_ResultHttpProbe_Handler,
		},
		{
			MethodName: "ResultPorts",
			Handler:    _JobsRegistryService_ResultPorts_Handler,
		},
		{
			MethodName: "ResultVulnerabilities",
			Handler:    _JobsRegistryService_ResultVulnerabilities_Handler,
		},
		{
			MethodName: "ResultScreenshot",
			Handler:    _JobsRegistryService_ResultScreenshot_Handler,
		},
		{
			MethodName: "ResultClassifier",
			Handler:    _JobsRegistryService_ResultClassifier_Handler,
		},
		{
			MethodName: "ResultAssistant",
			Handler:    _JobsRegistryService_ResultAssistant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jobs_registry.proto",
}
