name: Feature Request
title: 'Feature: '
labels: ['enhancement', 'feature']
assignees: []
description: Suggest a new feature or enhancement for the OpenASM platform
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a new feature! Please fill out the details below to help us understand your request better.
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature or enhancement you'd like to see
      placeholder: Provide a clear and concise description of what you want to happen
    validations:
      required: true
  - type: textarea
    id: problem-related
    attributes:
      label: Problem or Need
      description: What problem does this feature solve? What is the user need?
      placeholder: Explain the problem you're trying to solve or the need this feature addresses
    validations:
      required: false
  - type: textarea
    id: solution-proposal
    attributes:
      label: Proposed Solution
      description: Describe how you think this feature should work
      placeholder: Provide details about your proposed solution or approach
    validations:
      required: false
  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: Describe any alternative solutions or features you've considered
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Include any relevant information, links, or references
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
