// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: workers.proto

package workers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Token         *string                `protobuf:"bytes,3,opt,name=token,proto3,oneof" json:"token,omitempty"`
	Metadata      *WorkerMetadata        `protobuf:"bytes,4,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_workers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *JoinRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *JoinRequest) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *JoinRequest) GetMetadata() *WorkerMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type WorkerMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Os            *string                `protobuf:"bytes,2,opt,name=os,proto3,oneof" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMetadata) Reset() {
	*x = WorkerMetadata{}
	mi := &file_workers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMetadata) ProtoMessage() {}

func (x *WorkerMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMetadata.ProtoReflect.Descriptor instead.
func (*WorkerMetadata) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerMetadata) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *WorkerMetadata) GetOs() string {
	if x != nil && x.Os != nil {
		return *x.Os
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	WorkerToken   string                 `protobuf:"bytes,2,opt,name=worker_token,json=workerToken,proto3" json:"worker_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_workers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{2}
}

func (x *JoinResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JoinResponse) GetWorkerToken() string {
	if x != nil {
		return x.WorkerToken
	}
	return ""
}

type AliveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerToken   string                 `protobuf:"bytes,1,opt,name=worker_token,json=workerToken,proto3" json:"worker_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliveRequest) Reset() {
	*x = AliveRequest{}
	mi := &file_workers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveRequest) ProtoMessage() {}

func (x *AliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveRequest.ProtoReflect.Descriptor instead.
func (*AliveRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{3}
}

func (x *AliveRequest) GetWorkerToken() string {
	if x != nil {
		return x.WorkerToken
	}
	return ""
}

type AliveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	LastSeenAt    string                 `protobuf:"bytes,2,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliveResponse) Reset() {
	*x = AliveResponse{}
	mi := &file_workers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveResponse) ProtoMessage() {}

func (x *AliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveResponse.ProtoReflect.Descriptor instead.
func (*AliveResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{4}
}

func (x *AliveResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *AliveResponse) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

func (x *AliveResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_workers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{5}
}

type GetManifestResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DownloadToolsUrl string                 `protobuf:"bytes,1,opt,name=download_tools_url,json=downloadToolsUrl,proto3" json:"download_tools_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_workers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{6}
}

func (x *GetManifestResponse) GetDownloadToolsUrl() string {
	if x != nil {
		return x.DownloadToolsUrl
	}
	return ""
}

type DownloadToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadToolsRequest) Reset() {
	*x = DownloadToolsRequest{}
	mi := &file_workers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadToolsRequest) ProtoMessage() {}

func (x *DownloadToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadToolsRequest.ProtoReflect.Descriptor instead.
func (*DownloadToolsRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadToolsRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DownloadToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadToolsResponse) Reset() {
	*x = DownloadToolsResponse{}
	mi := &file_workers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadToolsResponse) ProtoMessage() {}

func (x *DownloadToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadToolsResponse.ProtoReflect.Descriptor instead.
func (*DownloadToolsResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadToolsResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *DownloadToolsResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DownloadToolsResponse) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

var File_workers_proto protoreflect.FileDescriptor

const file_workers_proto_rawDesc = "" +
	"\n" +
	"\rworkers.proto\x12\aworkers\"\xb0\x01\n" +
	"\vJoinRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x19\n" +
	"\x05token\x18\x03 \x01(\tH\x00R\x05token\x88\x01\x01\x128\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.workers.WorkerMetadataH\x01R\bmetadata\x88\x01\x01B\b\n" +
	"\x06_tokenB\v\n" +
	"\t_metadata\"N\n" +
	"\x0eWorkerMetadata\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x13\n" +
	"\x02os\x18\x02 \x01(\tH\x01R\x02os\x88\x01\x01B\a\n" +
	"\x05_nameB\x05\n" +
	"\x03_os\"N\n" +
	"\fJoinResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12!\n" +
	"\fworker_token\x18\x02 \x01(\tR\vworkerToken\"1\n" +
	"\fAliveRequest\x12!\n" +
	"\fworker_token\x18\x01 \x01(\tR\vworkerToken\"d\n" +
	"\rAliveResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12 \n" +
	"\flast_seen_at\x18\x02 \x01(\tR\n" +
	"lastSeenAt\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\"\x14\n" +
	"\x12GetManifestRequest\"C\n" +
	"\x13GetManifestResponse\x12,\n" +
	"\x12download_tools_url\x18\x01 \x01(\tR\x10downloadToolsUrl\"(\n" +
	"\x14DownloadToolsRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"W\n" +
	"\x15DownloadToolsResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof2\x9b\x02\n" +
	"\x0eWorkersService\x123\n" +
	"\x04Join\x12\x14.workers.JoinRequest\x1a\x15.workers.JoinResponse\x128\n" +
	"\x05Alive\x12\x15.workers.AliveRequest\x1a\x16.workers.AliveResponse0\x01\x12H\n" +
	"\vGetManifest\x12\x1b.workers.GetManifestRequest\x1a\x1c.workers.GetManifestResponse\x12P\n" +
	"\rDownloadTools\x12\x1d.workers.DownloadToolsRequest\x1a\x1e.workers.DownloadToolsResponse0\x01B\vZ\t./workersb\x06proto3"

var (
	file_workers_proto_rawDescOnce sync.Once
	file_workers_proto_rawDescData []byte
)

func file_workers_proto_rawDescGZIP() []byte {
	file_workers_proto_rawDescOnce.Do(func() {
		file_workers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workers_proto_rawDesc), len(file_workers_proto_rawDesc)))
	})
	return file_workers_proto_rawDescData
}

var file_workers_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_workers_proto_goTypes = []any{
	(*JoinRequest)(nil),           // 0: workers.JoinRequest
	(*WorkerMetadata)(nil),        // 1: workers.WorkerMetadata
	(*JoinResponse)(nil),          // 2: workers.JoinResponse
	(*AliveRequest)(nil),          // 3: workers.AliveRequest
	(*AliveResponse)(nil),         // 4: workers.AliveResponse
	(*GetManifestRequest)(nil),    // 5: workers.GetManifestRequest
	(*GetManifestResponse)(nil),   // 6: workers.GetManifestResponse
	(*DownloadToolsRequest)(nil),  // 7: workers.DownloadToolsRequest
	(*DownloadToolsResponse)(nil), // 8: workers.DownloadToolsResponse
}
var file_workers_proto_depIdxs = []int32{
	1, // 0: workers.JoinRequest.metadata:type_name -> workers.WorkerMetadata
	0, // 1: workers.WorkersService.Join:input_type -> workers.JoinRequest
	3, // 2: workers.WorkersService.Alive:input_type -> workers.AliveRequest
	5, // 3: workers.WorkersService.GetManifest:input_type -> workers.GetManifestRequest
	7, // 4: workers.WorkersService.DownloadTools:input_type -> workers.DownloadToolsRequest
	2, // 5: workers.WorkersService.Join:output_type -> workers.JoinResponse
	4, // 6: workers.WorkersService.Alive:output_type -> workers.AliveResponse
	6, // 7: workers.WorkersService.GetManifest:output_type -> workers.GetManifestResponse
	8, // 8: workers.WorkersService.DownloadTools:output_type -> workers.DownloadToolsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_workers_proto_init() }
func file_workers_proto_init() {
	if File_workers_proto != nil {
		return
	}
	file_workers_proto_msgTypes[0].OneofWrappers = []any{}
	file_workers_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workers_proto_rawDesc), len(file_workers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workers_proto_goTypes,
		DependencyIndexes: file_workers_proto_depIdxs,
		MessageInfos:      file_workers_proto_msgTypes,
	}.Build()
	File_workers_proto = out.File
	file_workers_proto_goTypes = nil
	file_workers_proto_depIdxs = nil
}
