// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: remote_execution.proto

package remote_execution

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemoteExecutionService_RemoteExecutionSession_FullMethodName = "/remote_exec.RemoteExecutionService/RemoteExecutionSession"
)

// RemoteExecutionServiceClient is the client API for RemoteExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemoteExecutionServiceClient interface {
	RemoteExecutionSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RemoteExecutionOutput, RemoteExecutionCommand], error)
}

type remoteExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteExecutionServiceClient(cc grpc.ClientConnInterface) RemoteExecutionServiceClient {
	return &remoteExecutionServiceClient{cc}
}

func (c *remoteExecutionServiceClient) RemoteExecutionSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RemoteExecutionOutput, RemoteExecutionCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RemoteExecutionService_ServiceDesc.Streams[0], RemoteExecutionService_RemoteExecutionSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RemoteExecutionOutput, RemoteExecutionCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteExecutionService_RemoteExecutionSessionClient = grpc.BidiStreamingClient[RemoteExecutionOutput, RemoteExecutionCommand]

// RemoteExecutionServiceServer is the server API for RemoteExecutionService service.
// All implementations must embed UnimplementedRemoteExecutionServiceServer
// for forward compatibility.
type RemoteExecutionServiceServer interface {
	RemoteExecutionSession(grpc.BidiStreamingServer[RemoteExecutionOutput, RemoteExecutionCommand]) error
	mustEmbedUnimplementedRemoteExecutionServiceServer()
}

// UnimplementedRemoteExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemoteExecutionServiceServer struct{}

func (UnimplementedRemoteExecutionServiceServer) RemoteExecutionSession(grpc.BidiStreamingServer[RemoteExecutionOutput, RemoteExecutionCommand]) error {
	return status.Error(codes.Unimplemented, "method RemoteExecutionSession not implemented")
}
func (UnimplementedRemoteExecutionServiceServer) mustEmbedUnimplementedRemoteExecutionServiceServer() {
}
func (UnimplementedRemoteExecutionServiceServer) testEmbeddedByValue() {}

// UnsafeRemoteExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteExecutionServiceServer will
// result in compilation errors.
type UnsafeRemoteExecutionServiceServer interface {
	mustEmbedUnimplementedRemoteExecutionServiceServer()
}

func RegisterRemoteExecutionServiceServer(s grpc.ServiceRegistrar, srv RemoteExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedRemoteExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemoteExecutionService_ServiceDesc, srv)
}

func _RemoteExecutionService_RemoteExecutionSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteExecutionServiceServer).RemoteExecutionSession(&grpc.GenericServerStream[RemoteExecutionOutput, RemoteExecutionCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteExecutionService_RemoteExecutionSessionServer = grpc.BidiStreamingServer[RemoteExecutionOutput, RemoteExecutionCommand]

// RemoteExecutionService_ServiceDesc is the grpc.ServiceDesc for RemoteExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoteExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remote_exec.RemoteExecutionService",
	HandlerType: (*RemoteExecutionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RemoteExecutionSession",
			Handler:       _RemoteExecutionService_RemoteExecutionSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "remote_execution.proto",
}
