// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: remote_execution.proto

package remote_execution

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteExecutionCommandType int32

const (
	RemoteExecutionCommandType_COMMAND_TYPE_UNKNOWN RemoteExecutionCommandType = 0
	RemoteExecutionCommandType_EXEC                 RemoteExecutionCommandType = 1
	RemoteExecutionCommandType_CANCEL               RemoteExecutionCommandType = 2
)

// Enum value maps for RemoteExecutionCommandType.
var (
	RemoteExecutionCommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNKNOWN",
		1: "EXEC",
		2: "CANCEL",
	}
	RemoteExecutionCommandType_value = map[string]int32{
		"COMMAND_TYPE_UNKNOWN": 0,
		"EXEC":                 1,
		"CANCEL":               2,
	}
)

func (x RemoteExecutionCommandType) Enum() *RemoteExecutionCommandType {
	p := new(RemoteExecutionCommandType)
	*p = x
	return p
}

func (x RemoteExecutionCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteExecutionCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_execution_proto_enumTypes[0].Descriptor()
}

func (RemoteExecutionCommandType) Type() protoreflect.EnumType {
	return &file_remote_execution_proto_enumTypes[0]
}

func (x RemoteExecutionCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteExecutionCommandType.Descriptor instead.
func (RemoteExecutionCommandType) EnumDescriptor() ([]byte, []int) {
	return file_remote_execution_proto_rawDescGZIP(), []int{0}
}

type RemoteExecutionOutputType int32

const (
	RemoteExecutionOutputType_OUTPUT_TYPE_UNKNOWN RemoteExecutionOutputType = 0
	RemoteExecutionOutputType_STDOUT              RemoteExecutionOutputType = 1
	RemoteExecutionOutputType_STDERR              RemoteExecutionOutputType = 2
	RemoteExecutionOutputType_EXIT                RemoteExecutionOutputType = 3
	RemoteExecutionOutputType_CONNECTED           RemoteExecutionOutputType = 4
	RemoteExecutionOutputType_DISCONNECTED        RemoteExecutionOutputType = 5
	RemoteExecutionOutputType_ERROR               RemoteExecutionOutputType = 6
)

// Enum value maps for RemoteExecutionOutputType.
var (
	RemoteExecutionOutputType_name = map[int32]string{
		0: "OUTPUT_TYPE_UNKNOWN",
		1: "STDOUT",
		2: "STDERR",
		3: "EXIT",
		4: "CONNECTED",
		5: "DISCONNECTED",
		6: "ERROR",
	}
	RemoteExecutionOutputType_value = map[string]int32{
		"OUTPUT_TYPE_UNKNOWN": 0,
		"STDOUT":              1,
		"STDERR":              2,
		"EXIT":                3,
		"CONNECTED":           4,
		"DISCONNECTED":        5,
		"ERROR":               6,
	}
)

func (x RemoteExecutionOutputType) Enum() *RemoteExecutionOutputType {
	p := new(RemoteExecutionOutputType)
	*p = x
	return p
}

func (x RemoteExecutionOutputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteExecutionOutputType) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_execution_proto_enumTypes[1].Descriptor()
}

func (RemoteExecutionOutputType) Type() protoreflect.EnumType {
	return &file_remote_execution_proto_enumTypes[1]
}

func (x RemoteExecutionOutputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteExecutionOutputType.Descriptor instead.
func (RemoteExecutionOutputType) EnumDescriptor() ([]byte, []int) {
	return file_remote_execution_proto_rawDescGZIP(), []int{1}
}

type RemoteExecutionCommand struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	SessionId     string                     `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       string                     `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Type          RemoteExecutionCommandType `protobuf:"varint,3,opt,name=type,proto3,enum=remote_exec.RemoteExecutionCommandType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteExecutionCommand) Reset() {
	*x = RemoteExecutionCommand{}
	mi := &file_remote_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteExecutionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteExecutionCommand) ProtoMessage() {}

func (x *RemoteExecutionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_remote_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteExecutionCommand.ProtoReflect.Descriptor instead.
func (*RemoteExecutionCommand) Descriptor() ([]byte, []int) {
	return file_remote_execution_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteExecutionCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RemoteExecutionCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RemoteExecutionCommand) GetType() RemoteExecutionCommandType {
	if x != nil {
		return x.Type
	}
	return RemoteExecutionCommandType_COMMAND_TYPE_UNKNOWN
}

type RemoteExecutionOutput struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	SessionId     string                    `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Type          RemoteExecutionOutputType `protobuf:"varint,2,opt,name=type,proto3,enum=remote_exec.RemoteExecutionOutputType" json:"type,omitempty"`
	Data          []byte                    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ExitCode      int32                     `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteExecutionOutput) Reset() {
	*x = RemoteExecutionOutput{}
	mi := &file_remote_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteExecutionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteExecutionOutput) ProtoMessage() {}

func (x *RemoteExecutionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_remote_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteExecutionOutput.ProtoReflect.Descriptor instead.
func (*RemoteExecutionOutput) Descriptor() ([]byte, []int) {
	return file_remote_execution_proto_rawDescGZIP(), []int{1}
}

func (x *RemoteExecutionOutput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RemoteExecutionOutput) GetType() RemoteExecutionOutputType {
	if x != nil {
		return x.Type
	}
	return RemoteExecutionOutputType_OUTPUT_TYPE_UNKNOWN
}

func (x *RemoteExecutionOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RemoteExecutionOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_remote_execution_proto protoreflect.FileDescriptor

const file_remote_execution_proto_rawDesc = "" +
	"\n" +
	"\x16remote_execution.proto\x12\vremote_exec\"\x8e\x01\n" +
	"\x16RemoteExecutionCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12;\n" +
	"\x04type\x18\x03 \x01(\x0e2'.remote_exec.RemoteExecutionCommandTypeR\x04type\"\xa3\x01\n" +
	"\x15RemoteExecutionOutput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12:\n" +
	"\x04type\x18\x02 \x01(\x0e2&.remote_exec.RemoteExecutionOutputTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode*L\n" +
	"\x1aRemoteExecutionCommandType\x12\x18\n" +
	"\x14COMMAND_TYPE_UNKNOWN\x10\x00\x12\b\n" +
	"\x04EXEC\x10\x01\x12\n" +
	"\n" +
	"\x06CANCEL\x10\x02*\x82\x01\n" +
	"\x19RemoteExecutionOutputType\x12\x17\n" +
	"\x13OUTPUT_TYPE_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x01\x12\n" +
	"\n" +
	"\x06STDERR\x10\x02\x12\b\n" +
	"\x04EXIT\x10\x03\x12\r\n" +
	"\tCONNECTED\x10\x04\x12\x10\n" +
	"\fDISCONNECTED\x10\x05\x12\t\n" +
	"\x05ERROR\x10\x062\x7f\n" +
	"\x16RemoteExecutionService\x12e\n" +
	"\x16RemoteExecutionSession\x12\".remote_exec.RemoteExecutionOutput\x1a#.remote_exec.RemoteExecutionCommand(\x010\x01B\x14Z\x12./remote_executionb\x06proto3"

var (
	file_remote_execution_proto_rawDescOnce sync.Once
	file_remote_execution_proto_rawDescData []byte
)

func file_remote_execution_proto_rawDescGZIP() []byte {
	file_remote_execution_proto_rawDescOnce.Do(func() {
		file_remote_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remote_execution_proto_rawDesc), len(file_remote_execution_proto_rawDesc)))
	})
	return file_remote_execution_proto_rawDescData
}

var file_remote_execution_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_remote_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_remote_execution_proto_goTypes = []any{
	(RemoteExecutionCommandType)(0), // 0: remote_exec.RemoteExecutionCommandType
	(RemoteExecutionOutputType)(0),  // 1: remote_exec.RemoteExecutionOutputType
	(*RemoteExecutionCommand)(nil),  // 2: remote_exec.RemoteExecutionCommand
	(*RemoteExecutionOutput)(nil),   // 3: remote_exec.RemoteExecutionOutput
}
var file_remote_execution_proto_depIdxs = []int32{
	0, // 0: remote_exec.RemoteExecutionCommand.type:type_name -> remote_exec.RemoteExecutionCommandType
	1, // 1: remote_exec.RemoteExecutionOutput.type:type_name -> remote_exec.RemoteExecutionOutputType
	3, // 2: remote_exec.RemoteExecutionService.RemoteExecutionSession:input_type -> remote_exec.RemoteExecutionOutput
	2, // 3: remote_exec.RemoteExecutionService.RemoteExecutionSession:output_type -> remote_exec.RemoteExecutionCommand
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_remote_execution_proto_init() }
func file_remote_execution_proto_init() {
	if File_remote_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remote_execution_proto_rawDesc), len(file_remote_execution_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remote_execution_proto_goTypes,
		DependencyIndexes: file_remote_execution_proto_depIdxs,
		EnumInfos:         file_remote_execution_proto_enumTypes,
		MessageInfos:      file_remote_execution_proto_msgTypes,
	}.Build()
	File_remote_execution_proto = out.File
	file_remote_execution_proto_goTypes = nil
	file_remote_execution_proto_depIdxs = nil
}
