// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "remote_execution.proto" (package "remote_exec", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message remote_exec.RemoteExecutionCommand
 */
export interface RemoteExecutionCommand {
    /**
     * @generated from protobuf field: string session_id = 1
     */
    sessionId: string;
    /**
     * @generated from protobuf field: string command = 2
     */
    command: string;
    /**
     * @generated from protobuf field: remote_exec.RemoteExecutionCommandType type = 3
     */
    type: RemoteExecutionCommandType;
}
/**
 * @generated from protobuf message remote_exec.RemoteExecutionOutput
 */
export interface RemoteExecutionOutput {
    /**
     * @generated from protobuf field: string session_id = 1
     */
    sessionId: string;
    /**
     * @generated from protobuf field: remote_exec.RemoteExecutionOutputType type = 2
     */
    type: RemoteExecutionOutputType;
    /**
     * @generated from protobuf field: bytes data = 3
     */
    data: Uint8Array;
    /**
     * @generated from protobuf field: int32 exit_code = 4
     */
    exitCode: number;
}
/**
 * @generated from protobuf enum remote_exec.RemoteExecutionCommandType
 */
export enum RemoteExecutionCommandType {
    /**
     * @generated from protobuf enum value: COMMAND_TYPE_UNKNOWN = 0;
     */
    COMMAND_TYPE_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: EXEC = 1;
     */
    EXEC = 1,
    /**
     * @generated from protobuf enum value: CANCEL = 2;
     */
    CANCEL = 2
}
/**
 * @generated from protobuf enum remote_exec.RemoteExecutionOutputType
 */
export enum RemoteExecutionOutputType {
    /**
     * @generated from protobuf enum value: OUTPUT_TYPE_UNKNOWN = 0;
     */
    OUTPUT_TYPE_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: STDOUT = 1;
     */
    STDOUT = 1,
    /**
     * @generated from protobuf enum value: STDERR = 2;
     */
    STDERR = 2,
    /**
     * @generated from protobuf enum value: EXIT = 3;
     */
    EXIT = 3,
    /**
     * @generated from protobuf enum value: CONNECTED = 4;
     */
    CONNECTED = 4,
    /**
     * @generated from protobuf enum value: DISCONNECTED = 5;
     */
    DISCONNECTED = 5,
    /**
     * @generated from protobuf enum value: ERROR = 6;
     */
    ERROR = 6
}
// @generated message type with reflection information, may provide speed optimized methods
class RemoteExecutionCommand$Type extends MessageType<RemoteExecutionCommand> {
    constructor() {
        super("remote_exec.RemoteExecutionCommand", [
            { no: 1, name: "session_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "command", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "type", kind: "enum", T: () => ["remote_exec.RemoteExecutionCommandType", RemoteExecutionCommandType] }
        ]);
    }
    create(value?: PartialMessage<RemoteExecutionCommand>): RemoteExecutionCommand {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sessionId = "";
        message.command = "";
        message.type = 0;
        if (value !== undefined)
            reflectionMergePartial<RemoteExecutionCommand>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RemoteExecutionCommand): RemoteExecutionCommand {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string session_id */ 1:
                    message.sessionId = reader.string();
                    break;
                case /* string command */ 2:
                    message.command = reader.string();
                    break;
                case /* remote_exec.RemoteExecutionCommandType type */ 3:
                    message.type = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RemoteExecutionCommand, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string session_id = 1; */
        if (message.sessionId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.sessionId);
        /* string command = 2; */
        if (message.command !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.command);
        /* remote_exec.RemoteExecutionCommandType type = 3; */
        if (message.type !== 0)
            writer.tag(3, WireType.Varint).int32(message.type);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_exec.RemoteExecutionCommand
 */
export const RemoteExecutionCommand = new RemoteExecutionCommand$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RemoteExecutionOutput$Type extends MessageType<RemoteExecutionOutput> {
    constructor() {
        super("remote_exec.RemoteExecutionOutput", [
            { no: 1, name: "session_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "enum", T: () => ["remote_exec.RemoteExecutionOutputType", RemoteExecutionOutputType] },
            { no: 3, name: "data", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 4, name: "exit_code", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<RemoteExecutionOutput>): RemoteExecutionOutput {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sessionId = "";
        message.type = 0;
        message.data = new Uint8Array(0);
        message.exitCode = 0;
        if (value !== undefined)
            reflectionMergePartial<RemoteExecutionOutput>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RemoteExecutionOutput): RemoteExecutionOutput {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string session_id */ 1:
                    message.sessionId = reader.string();
                    break;
                case /* remote_exec.RemoteExecutionOutputType type */ 2:
                    message.type = reader.int32();
                    break;
                case /* bytes data */ 3:
                    message.data = reader.bytes();
                    break;
                case /* int32 exit_code */ 4:
                    message.exitCode = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RemoteExecutionOutput, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string session_id = 1; */
        if (message.sessionId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.sessionId);
        /* remote_exec.RemoteExecutionOutputType type = 2; */
        if (message.type !== 0)
            writer.tag(2, WireType.Varint).int32(message.type);
        /* bytes data = 3; */
        if (message.data.length)
            writer.tag(3, WireType.LengthDelimited).bytes(message.data);
        /* int32 exit_code = 4; */
        if (message.exitCode !== 0)
            writer.tag(4, WireType.Varint).int32(message.exitCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message remote_exec.RemoteExecutionOutput
 */
export const RemoteExecutionOutput = new RemoteExecutionOutput$Type();
/**
 * @generated ServiceType for protobuf service remote_exec.RemoteExecutionService
 */
export const RemoteExecutionService = new ServiceType("remote_exec.RemoteExecutionService", [
    { name: "RemoteExecutionSession", serverStreaming: true, clientStreaming: true, options: {}, I: RemoteExecutionOutput, O: RemoteExecutionCommand }
]);
