// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "remote_execution.proto" (package "remote_exec", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { RemoteExecutionService } from "./remote_execution";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { RemoteExecutionCommand } from "./remote_execution";
import type { RemoteExecutionOutput } from "./remote_execution";
import type { DuplexStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service remote_exec.RemoteExecutionService
 */
export interface IRemoteExecutionServiceClient {
    /**
     * @generated from protobuf rpc: RemoteExecutionSession
     */
    remoteExecutionSession(options?: RpcOptions): DuplexStreamingCall<RemoteExecutionOutput, RemoteExecutionCommand>;
}
/**
 * @generated from protobuf service remote_exec.RemoteExecutionService
 */
export class RemoteExecutionServiceClient implements IRemoteExecutionServiceClient, ServiceInfo {
    typeName = RemoteExecutionService.typeName;
    methods = RemoteExecutionService.methods;
    options = RemoteExecutionService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: RemoteExecutionSession
     */
    remoteExecutionSession(options?: RpcOptions): DuplexStreamingCall<RemoteExecutionOutput, RemoteExecutionCommand> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoteExecutionOutput, RemoteExecutionCommand>("duplex", this._transport, method, opt);
    }
}
