// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "workers.proto" (package "workers", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message workers.JoinRequest
 */
export interface JoinRequest {
    /**
     * @generated from protobuf field: string api_key = 1
     */
    apiKey: string;
    /**
     * @generated from protobuf field: string signature = 2
     */
    signature: string;
    /**
     * @generated from protobuf field: optional string token = 3
     */
    token?: string;
}
/**
 * @generated from protobuf message workers.JoinResponse
 */
export interface JoinResponse {
    /**
     * @generated from protobuf field: string worker_id = 1
     */
    workerId: string;
    /**
     * @generated from protobuf field: string worker_token = 2
     */
    workerToken: string;
}
/**
 * @generated from protobuf message workers.AliveRequest
 */
export interface AliveRequest {
    /**
     * @generated from protobuf field: string worker_token = 1
     */
    workerToken: string;
}
/**
 * @generated from protobuf message workers.AliveResponse
 */
export interface AliveResponse {
    /**
     * @generated from protobuf field: bool alive = 1
     */
    alive: boolean;
    /**
     * @generated from protobuf field: string last_seen_at = 2
     */
    lastSeenAt: string;
    /**
     * @generated from protobuf field: string worker_id = 3
     */
    workerId: string;
}
/**
 * @generated from protobuf message workers.GetManifestRequest
 */
export interface GetManifestRequest {
}
/**
 * @generated from protobuf message workers.GetManifestResponse
 */
export interface GetManifestResponse {
    /**
     * @generated from protobuf field: string download_tools_url = 1
     */
    downloadToolsUrl: string;
}
/**
 * @generated from protobuf message workers.DownloadToolsRequest
 */
export interface DownloadToolsRequest {
    /**
     * @generated from protobuf field: string url = 1
     */
    url: string;
}
/**
 * @generated from protobuf message workers.DownloadToolsResponse
 */
export interface DownloadToolsResponse {
    /**
     * @generated from protobuf field: bytes chunk = 1
     */
    chunk: Uint8Array;
    /**
     * @generated from protobuf field: int32 offset = 2
     */
    offset: number;
    /**
     * @generated from protobuf field: bool eof = 3
     */
    eof: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class JoinRequest$Type extends MessageType<JoinRequest> {
    constructor() {
        super("workers.JoinRequest", [
            { no: 1, name: "api_key", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "signature", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "token", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<JoinRequest>): JoinRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.apiKey = "";
        message.signature = "";
        if (value !== undefined)
            reflectionMergePartial<JoinRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JoinRequest): JoinRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string api_key */ 1:
                    message.apiKey = reader.string();
                    break;
                case /* string signature */ 2:
                    message.signature = reader.string();
                    break;
                case /* optional string token */ 3:
                    message.token = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JoinRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string api_key = 1; */
        if (message.apiKey !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.apiKey);
        /* string signature = 2; */
        if (message.signature !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.signature);
        /* optional string token = 3; */
        if (message.token !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.token);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.JoinRequest
 */
export const JoinRequest = new JoinRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JoinResponse$Type extends MessageType<JoinResponse> {
    constructor() {
        super("workers.JoinResponse", [
            { no: 1, name: "worker_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "worker_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<JoinResponse>): JoinResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.workerId = "";
        message.workerToken = "";
        if (value !== undefined)
            reflectionMergePartial<JoinResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JoinResponse): JoinResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string worker_id */ 1:
                    message.workerId = reader.string();
                    break;
                case /* string worker_token */ 2:
                    message.workerToken = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JoinResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string worker_id = 1; */
        if (message.workerId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.workerId);
        /* string worker_token = 2; */
        if (message.workerToken !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.workerToken);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.JoinResponse
 */
export const JoinResponse = new JoinResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AliveRequest$Type extends MessageType<AliveRequest> {
    constructor() {
        super("workers.AliveRequest", [
            { no: 1, name: "worker_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AliveRequest>): AliveRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.workerToken = "";
        if (value !== undefined)
            reflectionMergePartial<AliveRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AliveRequest): AliveRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string worker_token */ 1:
                    message.workerToken = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AliveRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string worker_token = 1; */
        if (message.workerToken !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.workerToken);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.AliveRequest
 */
export const AliveRequest = new AliveRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AliveResponse$Type extends MessageType<AliveResponse> {
    constructor() {
        super("workers.AliveResponse", [
            { no: 1, name: "alive", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "last_seen_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "worker_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AliveResponse>): AliveResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.alive = false;
        message.lastSeenAt = "";
        message.workerId = "";
        if (value !== undefined)
            reflectionMergePartial<AliveResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AliveResponse): AliveResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool alive */ 1:
                    message.alive = reader.bool();
                    break;
                case /* string last_seen_at */ 2:
                    message.lastSeenAt = reader.string();
                    break;
                case /* string worker_id */ 3:
                    message.workerId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AliveResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool alive = 1; */
        if (message.alive !== false)
            writer.tag(1, WireType.Varint).bool(message.alive);
        /* string last_seen_at = 2; */
        if (message.lastSeenAt !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.lastSeenAt);
        /* string worker_id = 3; */
        if (message.workerId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.workerId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.AliveResponse
 */
export const AliveResponse = new AliveResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetManifestRequest$Type extends MessageType<GetManifestRequest> {
    constructor() {
        super("workers.GetManifestRequest", []);
    }
    create(value?: PartialMessage<GetManifestRequest>): GetManifestRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetManifestRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetManifestRequest): GetManifestRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetManifestRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.GetManifestRequest
 */
export const GetManifestRequest = new GetManifestRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetManifestResponse$Type extends MessageType<GetManifestResponse> {
    constructor() {
        super("workers.GetManifestResponse", [
            { no: 1, name: "download_tools_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetManifestResponse>): GetManifestResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.downloadToolsUrl = "";
        if (value !== undefined)
            reflectionMergePartial<GetManifestResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetManifestResponse): GetManifestResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string download_tools_url */ 1:
                    message.downloadToolsUrl = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetManifestResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string download_tools_url = 1; */
        if (message.downloadToolsUrl !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.downloadToolsUrl);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.GetManifestResponse
 */
export const GetManifestResponse = new GetManifestResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DownloadToolsRequest$Type extends MessageType<DownloadToolsRequest> {
    constructor() {
        super("workers.DownloadToolsRequest", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DownloadToolsRequest>): DownloadToolsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.url = "";
        if (value !== undefined)
            reflectionMergePartial<DownloadToolsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DownloadToolsRequest): DownloadToolsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string url */ 1:
                    message.url = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DownloadToolsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string url = 1; */
        if (message.url !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.url);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.DownloadToolsRequest
 */
export const DownloadToolsRequest = new DownloadToolsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DownloadToolsResponse$Type extends MessageType<DownloadToolsResponse> {
    constructor() {
        super("workers.DownloadToolsResponse", [
            { no: 1, name: "chunk", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "offset", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "eof", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<DownloadToolsResponse>): DownloadToolsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.chunk = new Uint8Array(0);
        message.offset = 0;
        message.eof = false;
        if (value !== undefined)
            reflectionMergePartial<DownloadToolsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DownloadToolsResponse): DownloadToolsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes chunk */ 1:
                    message.chunk = reader.bytes();
                    break;
                case /* int32 offset */ 2:
                    message.offset = reader.int32();
                    break;
                case /* bool eof */ 3:
                    message.eof = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DownloadToolsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes chunk = 1; */
        if (message.chunk.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.chunk);
        /* int32 offset = 2; */
        if (message.offset !== 0)
            writer.tag(2, WireType.Varint).int32(message.offset);
        /* bool eof = 3; */
        if (message.eof !== false)
            writer.tag(3, WireType.Varint).bool(message.eof);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.DownloadToolsResponse
 */
export const DownloadToolsResponse = new DownloadToolsResponse$Type();
/**
 * @generated ServiceType for protobuf service workers.WorkersService
 */
export const WorkersService = new ServiceType("workers.WorkersService", [
    { name: "Join", options: {}, I: JoinRequest, O: JoinResponse },
    { name: "Alive", serverStreaming: true, options: {}, I: AliveRequest, O: AliveResponse },
    { name: "GetManifest", options: {}, I: GetManifestRequest, O: GetManifestResponse },
    { name: "DownloadTools", serverStreaming: true, options: {}, I: DownloadToolsRequest, O: DownloadToolsResponse }
]);
