// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "workers.proto" (package "workers", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { WorkersService } from "./workers";
import type { DownloadToolsResponse } from "./workers";
import type { DownloadToolsRequest } from "./workers";
import type { GetManifestResponse } from "./workers";
import type { GetManifestRequest } from "./workers";
import type { AliveResponse } from "./workers";
import type { AliveRequest } from "./workers";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { JoinResponse } from "./workers";
import type { JoinRequest } from "./workers";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service workers.WorkersService
 */
export interface IWorkersServiceClient {
    /**
     * @generated from protobuf rpc: Join
     */
    join(input: JoinRequest, options?: RpcOptions): UnaryCall<JoinRequest, JoinResponse>;
    /**
     * @generated from protobuf rpc: Alive
     */
    alive(input: AliveRequest, options?: RpcOptions): ServerStreamingCall<AliveRequest, AliveResponse>;
    /**
     * @generated from protobuf rpc: GetManifest
     */
    getManifest(input: GetManifestRequest, options?: RpcOptions): UnaryCall<GetManifestRequest, GetManifestResponse>;
    /**
     * @generated from protobuf rpc: DownloadTools
     */
    downloadTools(input: DownloadToolsRequest, options?: RpcOptions): ServerStreamingCall<DownloadToolsRequest, DownloadToolsResponse>;
}
/**
 * @generated from protobuf service workers.WorkersService
 */
export class WorkersServiceClient implements IWorkersServiceClient, ServiceInfo {
    typeName = WorkersService.typeName;
    methods = WorkersService.methods;
    options = WorkersService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Join
     */
    join(input: JoinRequest, options?: RpcOptions): UnaryCall<JoinRequest, JoinResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<JoinRequest, JoinResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Alive
     */
    alive(input: AliveRequest, options?: RpcOptions): ServerStreamingCall<AliveRequest, AliveResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AliveRequest, AliveResponse>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetManifest
     */
    getManifest(input: GetManifestRequest, options?: RpcOptions): UnaryCall<GetManifestRequest, GetManifestResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetManifestRequest, GetManifestResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DownloadTools
     */
    downloadTools(input: DownloadToolsRequest, options?: RpcOptions): ServerStreamingCall<DownloadToolsRequest, DownloadToolsResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DownloadToolsRequest, DownloadToolsResponse>("serverStreaming", this._transport, method, opt, input);
    }
}
