/* eslint-disable @typescript-eslint/no-explicit-any */
import { config } from 'dotenv';
import { defineConfig } from 'orval';
import * as fs from 'fs';
import * as path from 'path';

config();

const INPUT_SPEC_PATH = path.resolve(__dirname, '../.open-api/open-api.json');
// orval reads from this patched copy; the raw spec is regenerated by core-api
// on every boot (main.ts) and must not be mutated.
const PATCHED_SPEC_PATH = path.resolve(
  __dirname,
  '../.open-api/open-api.patched.json',
);

/**
 * The backend regenerates .open-api/open-api.json from its live swagger on
 * every boot, and the audit export controller carries no response @Doc — so a
 * fresh spec declares an empty 200 and orval types the hook as `void`,
 * unusable for downloads. Patch the spec at generation time (mirrors the
 * storage-download convention: binary schema → Blob + responseType 'blob')
 * and generate from the patched copy, so every `task gen-api` yields a usable
 * auditEventsControllerExportAuditEvents hook.
 */
const applyAuditExportResponsePatch = (doc: any) => {
  const op = doc.paths?.['/api/workspaces/{id}/audit/export']?.get;
  if (!op) return;
  op.responses = op.responses ?? {};
  op.responses['200'] = {
    description:
      'CSV export of audit events (capped at 10,000 rows; beyond that the API returns 400 - narrow the filters)',
    content: {
      'text/csv': {
        schema: { type: 'string', format: 'binary' },
      },
    },
  };
};

const getInfiniteOverrides = () => {
  const operations: Record<string, any> = {};
  const inputPath = INPUT_SPEC_PATH;

  const fileContent = fs.readFileSync(inputPath, 'utf-8');
  const doc = JSON.parse(fileContent);

  Object.values(doc.paths || {}).forEach((pathItem: any) => {
    ['get', 'post', 'put', 'patch', 'delete'].forEach((method) => {
      if (pathItem[method]) {
        const operation = pathItem[method];
        const operationId = operation.operationId;

        if (!operationId) return;

        const allParams = [
          ...(pathItem.parameters || []),
          ...(operation.parameters || []),
        ];

        const hasPageParam = allParams.some((p: any) => p.name === 'page');

        if (hasPageParam) {
          operations[operationId] = {
            query: {
              useInfinite: true,
              useInfiniteQueryParam: 'page',
            },
          };
        }
      }
    });
  });

  return operations;
};

export default defineConfig({
  api: {
    output: {
      target: 'src/services/apis/gen/queries.ts',
      formatter: 'prettier',
      clean: true,
      client: 'react-query',
      httpClient: 'axios',
      override: {
        useTypeOverInterfaces: true,
        mutator: {
          path: 'src/services/apis/axios-client.ts',
          name: 'orvalClient',
        },
        operations: getInfiniteOverrides(),
      },
    },
    input: {
      target: buildPatchedSpec(),
    },
  },
});

/** Read the live spec, apply console-side response patches, write a patched
 * copy for orval to consume, and return its path. */
function buildPatchedSpec(): string {
  const fileContent = fs.readFileSync(INPUT_SPEC_PATH, 'utf-8');
  const doc = JSON.parse(fileContent);
  applyAuditExportResponsePatch(doc);
  fs.writeFileSync(PATCHED_SPEC_PATH, JSON.stringify(doc));
  return PATCHED_SPEC_PATH;
}
