version: "3"

vars:
  replicas: "{{.replicas | default 1}}"
  apiKey: "{{.apiKey | default .API_KEY}}"
  maxJobs: "{{.maxJobs | default .MAX_JOBS}}"

tasks:
  dev:
    env:
      API_KEY: "{{.apiKey}}"
      MAX_JOBS: "{{.maxJobs}}"
    cmds:
      - |
        for i in $(seq 1 {{.replicas}}); do
          echo "Starting worker $i"
          bun --watch index.ts &
        done
        wait
    silent: false

  install:
    cmds:
      - bun install
  clean:
    cmds:
      - rm -rf ./husky
      - rm -rf ./node_modules

  tools:
    cmds:
      - go install github.com/projectdiscovery/httpx/cmd/httpx@v1.7.1
      - go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@v2.8.0
      - go install github.com/projectdiscovery/nuclei/v3/cmd/nuclei@v3.4.10
      - go install github.com/projectdiscovery/dnsx/cmd/dnsx@v1.2.2
      - go install github.com/projectdiscovery/naabu/v2/cmd/naabu@v2.3.5
