version: "3"

tasks:
  dev:
    deps:
      - dev:subfinder
      - dev:naabu

  dev:subfinder:
    cmds:
      - NAME=subfinder bun --watch index.ts
    silent: true

  dev:naabu:
    cmds:
      - NAME=naabu bun --watch index.ts
    silent: true
