version: "3"

tasks:
  dev:
    deps:
      - dev:subfinder
      - dev:naabu

  dev:subfinder:
    cmds:
      - NAME=subfinder MAX_JOBS=10 bun --watch index.ts
    silent: true

  dev:naabu:
    cmds:
      - NAME=naabu MAX_JOBS=10 bun --watch index.ts
    silent: true
