import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateIndexes1780236911541 implements MigrationInterface {
    name = 'CreateIndexes1780236911541'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "agent_mcp_configs" ALTER COLUMN "configJson" SET DEFAULT '{"mcpServers":{}}'`);
        await queryRunner.query(`CREATE INDEX "IDX_asset_tags_tag" ON "asset_services_tags" ("tag") `);
        await queryRunner.query(`CREATE INDEX "IDX_asset_tags_assetServiceId" ON "asset_services_tags" ("assetServiceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_vuln_createdAt" ON "vulnerabilities" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_vuln_severity_isArchived" ON "vulnerabilities" ("severity", "isArchived") `);
        await queryRunner.query(`CREATE INDEX "IDX_vuln_jobHistoryId" ON "vulnerabilities" ("jobHistoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_vuln_tool" ON "vulnerabilities" ("toolId") `);
        await queryRunner.query(`CREATE INDEX "IDX_vuln_asset" ON "vulnerabilities" ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ni_workerId" ON "network_interfaces" ("workerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_workers_internalNetworkId" ON "workers" ("internalNetworkId") `);
        await queryRunner.query(`CREATE INDEX "IDX_workers_toolId" ON "workers" ("toolId") `);
        await queryRunner.query(`CREATE INDEX "IDX_workers_workspaceId" ON "workers" ("workspaceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_workers_token" ON "workers" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_wt_workspaceId" ON "workspace_tools" ("workspaceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_wt_toolId_workspaceId" ON "workspace_tools" ("toolId", "workspaceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_job_error_logs_jobId" ON "job_error_log" ("jobId") `);
        await queryRunner.query(`CREATE INDEX "IDX_jobs_category_status" ON "jobs" ("category", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_jobs_assetServiceId" ON "jobs" ("assetServiceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_jobs_jobHistoryId" ON "jobs" ("jobHistoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_jobs_workerId_status" ON "jobs" ("workerId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_jobs_tool" ON "jobs" ("toolId") `);
        await queryRunner.query(`CREATE INDEX "IDX_jobs_asset_status" ON "jobs" ("assetId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_jobs_status_priority_createdAt" ON "jobs" ("status", "priority", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_http_host" ON "http_responses" ("host") `);
        await queryRunner.query(`CREATE INDEX "IDX_http_jobHistoryId" ON "http_responses" ("jobHistoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ports_jobHistoryId" ON "ports" ("jobHistoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ports_assetId" ON "ports" ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_job_histories_workflow" ON "job_histories" ("workflowId") `);
        await queryRunner.query(`CREATE INDEX "IDX_workflows_workspaceId" ON "workflows" ("workspaceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_agw_workflowId" ON "asset_group_workflows" ("workflowId") `);
        await queryRunner.query(`CREATE INDEX "IDX_agw_assetGroupId" ON "asset_group_workflows" ("assetGroupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_aga_assetId" ON "assets_group_assets" ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_aga_assetGroupId" ON "assets_group_assets" ("assetGroupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_assets_targetId_isEnabled" ON "assets" ("targetId", "isEnabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_assets_targetId" ON "assets" ("targetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_wt_targetId" ON "workspace_targets" ("targetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_targets_scanSchedule_jobId" ON "targets" ("scanSchedule", "jobId") `);
        await queryRunner.query(`CREATE INDEX "IDX_targets_internalNetworkId" ON "targets" ("internalNetworkId") `);
        await queryRunner.query(`CREATE INDEX "IDX_targets_value" ON "targets" ("value") `);
        await queryRunner.query(`CREATE INDEX "IDX_inetwork_workspaceId" ON "internal_networks" ("workspaceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_search_hist_userId" ON "search_histories" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_wm_userId" ON "workspace_members" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_wm_workspace_user" ON "workspace_members" ("workspaceId", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_accounts_provider_account" ON "accounts" ("providerId", "accountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_accounts_userId" ON "accounts" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_sessions_expiresAt" ON "sessions" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_sessions_userId" ON "sessions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_stats_workspace_createdAt" ON "workspace_statistics" ("workspaceId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_templates_workspace" ON "templates" ("workspaceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_workspaces_owner" ON "workspaces" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_workspaceId" ON "notifications" ("workspaceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_notif_recipient_notifId" ON "notification_recipients" ("notificationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_notif_recipient_userId" ON "notification_recipients" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_issue_comments_issueId" ON "issue_comments" ("issueId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_issues_workspaceId_status" ON "issues" ("workspaceId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_agent_msg_conversationId" ON "agent_messages" ("conversationId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_agent_conv_createdBy" ON "agent_conversations" ("createdBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_agent_conv_workspaceId" ON "agent_conversations" ("workspaceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_llm_config_workspace_pref" ON "agent_llm_configs" ("workspaceId", "isPreferred") `);
        await queryRunner.query(`CREATE INDEX "IDX_llm_config_workspaceId" ON "agent_llm_configs" ("workspaceId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_llm_config_workspaceId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_llm_config_workspace_pref"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_agent_conv_workspaceId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_agent_conv_createdBy"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_agent_msg_conversationId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_issues_workspaceId_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_issue_comments_issueId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notif_recipient_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notif_recipient_notifId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_workspaceId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workspaces_owner"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_templates_workspace"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stats_workspace_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_sessions_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_sessions_expiresAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_accounts_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_accounts_provider_account"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wm_workspace_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wm_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_search_hist_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inetwork_workspaceId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_targets_value"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_targets_internalNetworkId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_targets_scanSchedule_jobId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wt_targetId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_assets_targetId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_assets_targetId_isEnabled"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aga_assetGroupId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aga_assetId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_agw_assetGroupId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_agw_workflowId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workflows_workspaceId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_job_histories_workflow"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ports_assetId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ports_jobHistoryId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_http_jobHistoryId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_http_host"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_jobs_status_priority_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_jobs_asset_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_jobs_tool"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_jobs_workerId_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_jobs_jobHistoryId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_jobs_assetServiceId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_jobs_category_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_job_error_logs_jobId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wt_toolId_workspaceId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wt_workspaceId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workers_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workers_workspaceId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workers_toolId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workers_internalNetworkId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ni_workerId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vuln_asset"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vuln_tool"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vuln_jobHistoryId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vuln_severity_isArchived"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vuln_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_asset_tags_assetServiceId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_asset_tags_tag"`);
        await queryRunner.query(`ALTER TABLE "agent_mcp_configs" ALTER COLUMN "configJson" SET DEFAULT '{"mcpServers": {}}'`);
    }

}
