name: Build OASM Unstable

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/oasm

jobs:
  build:
#    runs-on: self-hosted
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to image repository
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --tag ${{ env.IMAGE_NAME }}-core-api:latest \
            --tag ${{ env.IMAGE_NAME }}-core-api:${GITHUB_SHA::7} \
            --file ./Dockerfile ./core-api

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --tag ${{ env.IMAGE_NAME }}-worker:latest \
            --tag ${{ env.IMAGE_NAME }}-worker:${GITHUB_SHA::7} \
            --file ./Dockerfile ./worker