name: Build OASM Stable

on:
  push:
#    release:
#      types: [published]
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: oasm/oasm

jobs:
  build:
#    runs-on: self-hosted
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to image repository
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            --tag ${{ env.IMAGE_NAME }}-api:latest \
            --tag ${{ env.IMAGE_NAME }}-api:${{ github.ref_name }} \
            --file ./core-api/Dockerfile ./core-api

          docker buildx build \
            --platform linux/amd64 \
            --push \
            --tag ${{ env.IMAGE_NAME }}-worker:latest \
            --tag ${{ env.IMAGE_NAME }}-worker:${{ github.ref_name }} \
            --file ./worker/Dockerfile ./worker