name: Build OASM Unstable

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: oasm/oasm

jobs:
  build:
#    runs-on: self-hosted
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      security-events: write

    strategy:
      matrix:
        service: [api, worker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to image repository
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx with cache support
        run: |
          docker buildx create --name mybuilder --driver docker-container --use
          docker buildx inspect --bootstrap

      - name: Build and push
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            --cache-from=type=registry,ref=${{ env.IMAGE_NAME }}-${{ matrix.service }}:buildcache \
            --cache-to=type=registry,ref=${{ env.IMAGE_NAME }}-${{ matrix.service }}:buildcache,mode=max \
            --tag ${{ env.IMAGE_NAME }}-${{ matrix.service }}:dev \
            --file ./${{ matrix.service == 'api' && 'core-api' || matrix.service }}/Dockerfile \
            ./${{ matrix.service == 'api' && 'core-api' || matrix.service }}

      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-db
          restore-keys: |
            ${{ runner.os }}-trivy-db

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.0
        with:
          image-ref: '${{ env.IMAGE_NAME }}-${{ matrix.service }}:dev'
          format: 'sarif'
          output: 'trivy-results.${{ matrix.service }}.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.${{ matrix.service }}.sarif'

