name: Build OASM Unstable

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: oasm/oasm

jobs:
  build:
#    runs-on: self-hosted
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to image repository
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            --tag ${{ env.IMAGE_NAME }}-api:dev \
            --file ./core-api/Dockerfile ./core-api

          docker buildx build \
            --platform linux/amd64 \
            --push \
            --tag ${{ env.IMAGE_NAME }}-worker:dev \
            --file ./worker/Dockerfile ./worker