name: Check Lint

on:
  push:
    branches:
      - '**'
    paths:
      - 'core-api/**'
      - 'console/**'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'package.json'
      - 'tsconfig*.json'
  pull_request:
    branches:
      - '**'
    paths:
      - 'core-api/**'
      - 'console/**'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'package.json'
      - 'tsconfig*.json'

jobs:
  lint:
    name: Check Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [core-api, console]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm run lint --filter=${{ matrix.service }}
